#!/usr/bin/env python3
"""Expose the locally running ERP to a client over a Cloudflare Quick Tunnel.

Starts a basic-auth-gated backend, opens an anonymous HTTPS tunnel, prints the
shareable URL and credentials, and shuts everything down on Ctrl+C. Standard
library only (docs/DEMO_SHARING_PLAN.md). Run from anywhere:

    python scripts/share_demo.py
"""
from __future__ import annotations

import argparse
import base64
import os
import re
import secrets
import shutil
import signal
import string
import subprocess
import sys
import threading
import time
import urllib.error
import urllib.request
from pathlib import Path

# ---------------------------------------------------------------- CONFIG
ROOT = Path(__file__).resolve().parents[1]
BACKEND_DIR = ROOT / "backend"
FRONTEND_DIR = ROOT / "frontend"
BUILD_OUTPUT = FRONTEND_DIR / "dist"
APP_IMPORT = "app.main:app"
HOST, PORT = "127.0.0.1", 8000
HEALTH_PATH = "/health"           # root route, NOT /api/v1/health
API_BASE_FOR_BUILD = "/api/v1"    # origin-relative base baked into the SPA build
ENV_FILE = ROOT / ".env.demo"
FRONTEND_PROD_ENV = FRONTEND_DIR / ".env.production"
BACKEND_LOG = ROOT / ".demo-backend.log"
# ------------------------------------------------------------------------

TUNNEL_URL_RE = re.compile(rb"https://[a-z0-9][a-z0-9-]*\.trycloudflare\.com")
_procs: list[subprocess.Popen] = []


def fail(message: str) -> None:
    print(f"\n  ERROR  {message}\n", file=sys.stderr)
    shutdown()
    sys.exit(1)


def preflight() -> None:
    """Fail fast on the two known Quick-Tunnel blockers."""
    if shutil.which("cloudflared") is None:
        fail(
            "cloudflared is not installed.\n"
            "         macOS:    brew install cloudflared\n"
            "         Windows:  winget install --id Cloudflare.cloudflared\n"
            "         Linux:    install the .deb from the cloudflared GitHub releases page"
        )
    if (Path.home() / ".cloudflared" / "config.yml").exists():
        fail(
            "~/.cloudflared/config.yml exists — it forces named-tunnel mode and "
            "breaks `cloudflared tunnel --url`. Rename it, then re-run."
        )


def load_or_create_credentials() -> tuple[str, str]:
    """Read .env.demo, generating a fresh password on first run."""
    if ENV_FILE.exists():
        values = {}
        for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, value = line.partition("=")
                values[key.strip()] = value.strip()
        user = values.get("DEMO_GATE_USER")
        password = values.get("DEMO_GATE_PASSWORD")
        if user and password:
            return user, password

    alphabet = string.ascii_letters + string.digits
    password = "".join(secrets.choice(alphabet) for _ in range(24))
    user = "client"
    ENV_FILE.write_text(
        "# Generated by scripts/share_demo.py — gitignored, do not commit.\n"
        "# Delete this file to rotate the demo credentials.\n"
        f"DEMO_GATE_USER={user}\n"
        f"DEMO_GATE_PASSWORD={password}\n",
        encoding="utf-8",
    )
    return user, password


def ensure_prod_env() -> None:
    """Bake an origin-relative API base into the production build.

    frontend/src/shared/api.ts falls back to http://localhost:8000/api/v1, which
    breaks behind the tunnel. .env.production is gitignored, so we (re)generate it
    every run — deterministic and fresh-clone-safe. Only read in production mode,
    so `npm run dev` is unaffected.
    """
    FRONTEND_PROD_ENV.write_text(
        f"VITE_API_BASE={API_BASE_FOR_BUILD}\n", encoding="utf-8"
    )


def build_frontend() -> None:
    npm = shutil.which("npm") or shutil.which("npm.cmd")
    if npm is None:
        fail("npm not found on PATH — cannot build the frontend.")
    ensure_prod_env()
    print("  ->  Building the production frontend bundle (this takes a minute)…")
    result = subprocess.run([npm, "run", "build"], cwd=FRONTEND_DIR)
    if result.returncode != 0:
        fail("Frontend build failed. Fix the build, then re-run.")
    if not BUILD_OUTPUT.is_dir():
        fail(f"Build reported success but {BUILD_OUTPUT} does not exist.")


def start_backend(user: str, password: str) -> subprocess.Popen:
    env = {
        **os.environ,
        "DEMO_GATE_ENABLED": "1",
        "DEMO_GATE_USER": user,
        "DEMO_GATE_PASSWORD": password,
        "SERVE_FRONTEND": "1",
    }
    cmd = [
        sys.executable, "-m", "uvicorn", APP_IMPORT,
        "--host", HOST, "--port", str(PORT),
        "--proxy-headers", "--forwarded-allow-ips", "*",
    ]
    print("  ->  Starting the gated backend…")
    # Redirect the backend's own logs to a file: otherwise its (possibly DEBUG)
    # output floods this console and interleaves into — corrupting — the banner.
    # Tail .demo-backend.log to debug a failed start.
    log = open(BACKEND_LOG, "w", encoding="utf-8")
    proc = subprocess.Popen(
        cmd, cwd=BACKEND_DIR, env=env, stdout=log, stderr=subprocess.STDOUT
    )
    log.close()  # the child holds its own dup of the fd; we don't need ours
    return proc


def wait_for_backend(user: str, password: str, timeout: int = 60) -> None:
    token = base64.b64encode(f"{user}:{password}".encode()).decode()
    request = urllib.request.Request(
        f"http://{HOST}:{PORT}{HEALTH_PATH}",
        headers={"Authorization": f"Basic {token}"},
    )
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            with urllib.request.urlopen(request, timeout=3) as response:
                if response.status == 200:
                    print("  ->  Backend is up and the gate is active.")
                    return
        except (urllib.error.URLError, urllib.error.HTTPError, OSError):
            time.sleep(1)
    fail(f"Backend did not become healthy within {timeout}s — see {BACKEND_LOG} "
         "(is MongoDB running? /health returns 503 until it is).")


def wait_for_tunnel(url: str, user: str, password: str, timeout: int = 120) -> None:
    """Poll the PUBLIC url until Cloudflare's edge can route to our origin.

    A Quick Tunnel prints its URL before the edge connection is actually routable
    (warmup is variable — a few seconds up to ~a minute); a request sent in that
    window gets a connection reset / 502. We probe with credentials and wait for a
    real 200 so the URL we hand the client works on the first click. Non-fatal: if
    it never confirms we print the banner anyway.
    """
    token = base64.b64encode(f"{user}:{password}".encode()).decode()
    request = urllib.request.Request(
        f"{url}{HEALTH_PATH}", headers={"Authorization": f"Basic {token}"}
    )
    print("  ->  Waiting for the tunnel edge to become routable "
          "(can take up to a minute)", end="", flush=True)
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            with urllib.request.urlopen(request, timeout=5) as response:
                if response.status == 200:
                    print("  live.")
                    return
        except (urllib.error.URLError, OSError):
            pass  # reset / 502 while the edge warms up — keep trying
        print(".", end="", flush=True)
        time.sleep(2)
    print("\n  ->  (not confirmed yet; it usually becomes routable within a few "
          "more seconds — the URL below is still correct)")


def start_tunnel() -> tuple[subprocess.Popen, str]:
    print("  ->  Opening the Cloudflare Quick Tunnel…")
    process = subprocess.Popen(
        ["cloudflared", "tunnel", "--url", f"http://{HOST}:{PORT}", "--no-autoupdate"],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,   # cloudflared logs the URL on stderr
        bufsize=0,
    )
    url_box: dict[str, str] = {}

    def reader() -> None:
        for raw in iter(process.stdout.readline, b""):
            if "url" not in url_box:
                match = TUNNEL_URL_RE.search(raw)
                if match:
                    url_box["url"] = match.group(0).decode()

    threading.Thread(target=reader, daemon=True).start()

    deadline = time.time() + 45
    while time.time() < deadline:
        if "url" in url_box:
            return process, url_box["url"]
        if process.poll() is not None:
            fail("cloudflared exited before producing a URL.")
        time.sleep(0.5)
    fail("Timed out waiting for a trycloudflare.com URL.")


def banner(url: str, user: str, password: str) -> None:
    line = "=" * 68
    print(
        f"\n{line}\n"
        f"  DEMO IS LIVE — send this to the client\n"
        f"{line}\n\n"
        f"  URL       {url}\n"
        f"  Username  {user}\n"
        f"  Password  {password}\n\n"
        f"  Send the URL and the password over two different channels.\n"
        f"  This URL is temporary and changes every time you run this script.\n"
        f"  The demo dies when this terminal closes or the laptop sleeps.\n\n"
        f"  Press Ctrl+C to stop sharing.\n"
        f"{line}\n"
    )


def shutdown(*_args) -> None:
    for process in reversed(_procs):
        if process.poll() is None:
            process.terminate()
    deadline = time.time() + 10
    for process in _procs:
        remaining = max(0, deadline - time.time())
        try:
            process.wait(timeout=remaining)
        except subprocess.TimeoutExpired:
            process.kill()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--skip-build", action="store_true",
                        help="reuse the existing frontend build")
    args = parser.parse_args()

    signal.signal(signal.SIGINT, lambda *a: (shutdown(), sys.exit(0)))

    preflight()
    user, password = load_or_create_credentials()
    if not args.skip_build:
        build_frontend()
    elif not BUILD_OUTPUT.is_dir():
        fail("--skip-build was passed but no existing build was found.")

    _procs.append(start_backend(user, password))
    wait_for_backend(user, password)
    tunnel, url = start_tunnel()
    _procs.append(tunnel)
    wait_for_tunnel(url, user, password)
    banner(url, user, password)

    try:
        while all(p.poll() is None for p in _procs):
            time.sleep(1)
        print("\n  A child process exited. Shutting down.")
    finally:
        shutdown()


if __name__ == "__main__":
    main()
